/*
 * Kashoo Echo
 *
 * This is a simple two-endpoint echo/golang project.
 *
 * API version: 1.0
 * Contact: domgolonka@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HandlersError struct {
	Code int32 `json:"code,omitempty"`
	Field string `json:"field,omitempty"`
	Message string `json:"message,omitempty"`
}
