openapi: 3.0.1
info:
  title: Kashoo Echo
  description: This is a simple two-endpoint echo/golang project.
  contact:
    name: Dominik Golonka
    url: http://www.github.com/domgolonka
    email: domgolonka@gmail.com
  license: {}
  version: "1.0"
servers:
- url: http://127.0.0.1:1323/
paths:
  /geolocate/{ip}:
    get:
      tags:
      - geolocation
      summary: Gets the location data of an IPv4 or Ipv6.
      description: Requests an IP address and returns the location data using the
        ipgeolocation.io API.
      operationId: get-geo-location-from-ip
      parameters:
      - name: ip
        in: path
        description: IP Address
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                x-content-type: application/json
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handlers.Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/handlers.Error'
components:
  schemas:
    handlers.Error:
      type: object
      properties:
        code:
          type: integer
        field:
          type: string
        message:
          type: string
